### ISSUE TITLE
CI: make command not found

### ISSUE THREAD

**Issue by rhagenson** [ponylang/library-scaffolding-generator#4]
Ran through the steps to get CircleCI setup on a project and it is failing against Docker ponylang/ponyc:release and ponylang/ponyc:latest as neither has make installed. Not sure if the plan is to migrate away from make toward stable/corral or not, but wanted to raise the issue to draw attention to the most appropriate fix.

**Comment by rhagenson** [comment]
I just looked at the [Dockerfile](https://hub.docker.com/r/ponylang/ponyc/dockerfile) for ponyc and it uses make so I am confused why my CI is failing to find make?

**Comment by SeanTAllen** [comment]
`make` is definitely part of the image. Can you share an example of a failing run?

**Comment by rhagenson** [comment]
This is the project that is failing: https://github.com/pony-bio/pony-bio and the CI: https://circleci.com/gh/pony-bio/pony-bio

**Comment by SeanTAllen** [comment]
It is missing from the glibc based images. It's there in the musl ones. I'm updating the glibc ones to have make as well. This didn't come up for any pony projects because we use these images rather than those directly: https://github.com/ponylang/shared-docker
